# TipJar/docker-compose.yml


services:
  postgres_db: # Nazwa serwisu PostgreSQL
    image: postgres:15-alpine
    container_name: tipjar_postgres_db_mvp
    env_file: backend/.env
    ports:
      - "${POSTGRES_DB_PORT:-5432}:5432"
    volumes:
      - tipjar_postgres_data_mvp:/var/lib/postgresql/data
    restart: unless-stopped

  redis_cache: # Nazwa serwisu Redis
    image: redis:7-alpine
    container_name: tipjar_redis_cache
    ports:
      - "6379:6379"
    volumes:
      - tipjar_redis_data:/data
    restart: unless-stopped

volumes: # Definicje nazwanych wolumenów
  tipjar_postgres_data_mvp: # Wolumen dla PostgreSQL
    driver: local
  tipjar_redis_data: # Wolumen dla Redis
    driver: local
