# TipJar/backend/docker-compose.yml
version: '3.8' # Wersja składni Docker Compose

services:
  postgres_db: # Nazwa serwisu PostgreSQL
    image: postgres:15-alpine
    container_name: tipjar_postgres_db_mvp
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER:-USER_DB_DOCKER_DEFAULT}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD:-PASSWORD_DB_DOCKER_DEFAULT}
      POSTGRES_DB: ${POSTGRES_DB_NAME:-tipjar_mvp_docker_db_default}
    ports:
      - "${POSTGRES_DB_PORT:-5432}:5432"
    volumes:
      - tipjar_postgres_data_mvp:/var/lib/postgresql/data
    restart: unless-stopped

  redis_cache: # Nazwa serwisu Redis
    image: redis:7-alpine
    container_name: tipjar_redis_cache
    ports:
      - "6379:6379"
    volumes:
      - tipjar_redis_data:/data
    restart: unless-stopped

volumes: # Definicje nazwanych wolumenów
  tipjar_postgres_data_mvp: # Wolumen dla PostgreSQL
    driver: local
  tipjar_redis_data:        # Wolumen dla Redis
    driver: local